/**
 * tests/challenger_verification.js
 * Verification script written by Challenger subagent for Milestone 3.
 * Tests markdown rendering edge cases, XSS safety, and dynamic route behavior.
 */

const fs = require('fs');
const path = require('path');
const Module = require('module');

// 1. Intercept require for react/jsx-runtime and next/navigation
const originalRequire = Module.prototype.require;
Module.prototype.require = function(id) {
  if (id === 'next/navigation') {
    return {
      useRouter: () => ({
        push: (url) => {
          // console.log(`[Mock Router] push to ${url}`);
        }
      }),
      notFound: () => {
        throw new Error('NEXT_NOT_FOUND');
      }
    };
  }
  if (id === 'react/jsx-runtime') {
    return {
      jsx: (type, props) => ({ type, props }),
      jsxs: (type, props) => ({ type, props })
    };
  }
  return originalRequire.apply(this, arguments);
};

// Import compiled services and pages
const { renderMarkdown, staticBlogs } = require('./challenger_out/services/blogService');
const BlogDetailPage = require('./challenger_out/app/blog/[id]/page').default;

const results = {
  markdown: [],
  xss: [],
  route: []
};

function testMarkdown(name, input, expectedFn) {
  try {
    const output = renderMarkdown(input);
    const passed = expectedFn(output);
    results.markdown.push({
      name,
      input: JSON.stringify(input),
      output: JSON.stringify(output),
      passed,
      error: null
    });
  } catch (err) {
    results.markdown.push({
      name,
      input: JSON.stringify(input),
      output: null,
      passed: false,
      error: err.message
    });
  }
}

function testXSS(name, input) {
  try {
    const output = renderMarkdown(input);
    
    // Find all raw HTML tags in output (e.g. <something>)
    const tags = output.match(/<[^>]+>/g) || [];
    
    // Check if there are any tags that are not generated by the parser
    const allowedTagStrings = [
      '<p>', '</p>', 
      '<h1>', '</h1>', 
      '<h2>', '</h2>', 
      '<h3>', '</h3>', 
      '<li>', '</li>', 
      '<code>', '</code>', 
      '<pre>', '</pre>', 
      '<pre><code>', '</code></pre>'
    ];
    
    const disallowedTags = tags.filter(tag => !allowedTagStrings.includes(tag));
    const isSafe = disallowedTags.length === 0;
    
    results.xss.push({
      name,
      input: JSON.stringify(input),
      output: JSON.stringify(output),
      passed: isSafe,
      details: isSafe ? "Safe (HTML escaped)" : `VULNERABLE (Found unescaped/unexpected tags: ${disallowedTags.join(', ')})`
    });
  } catch (err) {
    results.xss.push({
      name,
      input: JSON.stringify(input),
      output: null,
      passed: false,
      error: err.message
    });
  }
}

function testRoute(name, params, expectedStatus) {
  try {
    // Call the BlogDetailPage function directly
    const element = BlogDetailPage({ params });
    results.route.push({
      name,
      params: JSON.stringify(params),
      passed: expectedStatus === 'success',
      details: `Returned element type: ${element.type}`,
      error: null
    });
  } catch (err) {
    const isNotFound = err.message === 'NEXT_NOT_FOUND';
    const passed = (expectedStatus === 'notFound' && isNotFound) || (expectedStatus === 'error' && !isNotFound);
    results.route.push({
      name,
      params: JSON.stringify(params),
      passed,
      details: isNotFound ? "Triggered notFound()" : `Crashed: ${err.message}`,
      error: err.stack
    });
  }
}

console.log("Starting Challenger verification...");

// ==========================================
// 1. Markdown Parsing Verification
// ==========================================
testMarkdown("Empty string", "", (out) => out === "");
testMarkdown("Undefined input", undefined, (out) => out === "");
testMarkdown("Basic heading", "# Hello", (out) => out === "<h1>Hello</h1>");
testMarkdown("Heading 3 with list", "### Sub\n- Item 1", (out) => out.includes("<h3>Sub</h3>") && out.includes("<li>Item 1</li>"));
testMarkdown("Unmatched backtick", "some `unmatched block", (out) => out.includes("<p>some `unmatched block</p>"));
testMarkdown("Multiple inline code blocks", "use `a` and `b` here", (out) => out.includes("<code>a</code>") && out.includes("<code>b</code>"));

// Test placeholder recursion bug we found:
testMarkdown(
  "Placeholder recursion: code containing placeholder of another",
  "`__INLINE_CODE_PLACEHOLDER_1__` and `second code`",
  (out) => {
    // Correct output should contain both strings represented inside code tags
    return out.includes("<code>__INLINE_CODE_PLACEHOLDER_1__</code>") && out.includes("<code>second code</code>");
  }
);

// Test list-like items on 2nd line of code block bug we found:
testMarkdown(
  "List-like lines inside multiline code blocks (subsequent lines)",
  "```swift\nline 1\n- line 2 is list-like\n```",
  (out) => {
    // Should NOT contain <li> because it is inside <pre><code>
    return !out.includes("<li>");
  }
);

// ==========================================
// 2. XSS Safety Validation
// ==========================================
testXSS("Basic script tag", "<script>alert('XSS')</script>");
testXSS("Image with onerror", "<img src=x onerror=alert('XSS') />");
testXSS("Iframe with javascript URL", "<iframe src=\"javascript:alert('XSS')\"></iframe>");
testXSS("Anchor link with javascript URL", "<a href=\"javascript:alert('XSS')\">click</a>");
testXSS("Div with onload attribute", "<div onload=\"alert('XSS')\">hello</div>");
testXSS("SVG with onload", "<svg/onload=alert('XSS')>");
testXSS("Nested payload", "<div><script>alert(1)</script></div>");

// ==========================================
// 3. Dynamic Route Behavior Verification
// ==========================================
// Valid blog posts IDs in staticBlogs: "blog-1", "blog-2", "blog-3"
testRoute("Valid ID - blog-1", { id: "blog-1" }, "success");
testRoute("Valid ID - blog-2", { id: "blog-2" }, "success");
testRoute("Invalid ID - empty string", { id: "" }, "notFound");
testRoute("Invalid ID - non-existent", { id: "blog-999" }, "notFound");
testRoute("Invalid ID - null/undefined parameters", {}, "notFound");
testRoute("Invalid ID - malicious / injection ID", { id: "../../../etc/passwd" }, "notFound");

// Print results
console.log("\n========================================");
console.log("Markdown Verification Results:");
console.log("========================================");
results.markdown.forEach(r => {
  console.log(`[${r.passed ? "PASS" : "FAIL"}] ${r.name}`);
  console.log(`  Input:  ${r.input}`);
  console.log(`  Output: ${r.output}`);
  if (r.error) console.log(`  Error:  ${r.error}`);
});

console.log("\n========================================");
console.log("XSS Safety Verification Results:");
console.log("========================================");
results.xss.forEach(r => {
  console.log(`[${r.passed ? "PASS" : "FAIL"}] ${r.name}`);
  console.log(`  Input:  ${r.input}`);
  console.log(`  Details: ${r.details}`);
});

console.log("\n========================================");
console.log("Dynamic Route Verification Results:");
console.log("========================================");
results.route.forEach(r => {
  console.log(`[${r.passed ? "PASS" : "FAIL"}] ${r.name}`);
  console.log(`  Params:  ${r.params}`);
  console.log(`  Details: ${r.details}`);
  if (r.error && !r.passed) console.log(`  Error:   ${r.error}`);
});

const allPassed = 
  results.markdown.every(r => r.passed) &&
  results.xss.every(r => r.passed) &&
  results.route.every(r => r.passed);

console.log("\n========================================");
console.log(`Summary: ${allPassed ? "ALL PASSED" : "SOME FAILED"}`);
console.log("========================================\n");

if (!allPassed) {
  process.exit(1);
} else {
  process.exit(0);
}
